import { useEffect, useRef, useState } from 'react';
import { X, Check, LockKeyhole, ArrowLeft, ArrowRight, Building2 } from 'lucide-react';
import { apiFetch } from '../api';
const steps=['Business','Availability','Catalogue','Agent','Voice & model','Capabilities','Review'];
const blank={name:'',type:'Service and Appointment Booking',country:'United States',timezone:'America/New_York',industry:'',phone:'',email:'',website:'',address:'',description:''};
export default function OnboardingModal({isOpen,onClose,onCreated,mode,initialBusinessId}) {
  const [step,setStep]=useState(0),[business,setBusiness]=useState(blank),[existing,setExisting]=useState([]),[source,setSource]=useState('new');
  const [hours,setHours]=useState(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(day=>({day,open_time:'09:00',close_time:'17:00',closed:false})));
  const [noHours,setNoHours]=useState(false),[noCatalogue,setNoCatalogue]=useState(false),[services,setServices]=useState([{service_name:'',price:'',duration_minutes:30}]);
  const [agent,setAgent]=useState({name:'',role:'Customer service assistant',language:'en',first_message:''}),[voices,setVoices]=useState([]),[models,setModels]=useState([]),[voice,setVoice]=useState(''),[model,setModel]=useState('');
  const [features,setFeatures]=useState([]),[noFeatures,setNoFeatures]=useState(false),[accepted,setAccepted]=useState(false),[unavailable,setUnavailable]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null);
  const dialog=useRef(null);
  useEffect(()=>{if(!isOpen)return;let active=true;setStep(0);setResult(null);setError('');setBusiness({...blank});setAgent({name:'',role:'Customer service assistant',language:'en',first_message:''});setUnavailable({});setAccepted(false);setNoHours(false);setNoCatalogue(false);setNoFeatures(false);setFeatures([]);setServices([{service_name:'',price:'',duration_minutes:30}]);setVoice('');setModel('');setHours(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(day=>({day,open_time:'09:00',close_time:'17:00',closed:false})));
    Promise.all([apiFetch('/admin/businesses'),apiFetch('/admin/onboarding/voices'),apiFetch('/admin/onboarding/llms')]).then(([b,v,l])=>{if(!active)return;setExisting(b);setVoices(v.voices||[]);setModels(l.llms||[]);const found=b.find(x=>String(x.id)===String(initialBusinessId));if(found){setBusiness({...blank,...found});setSource('existing');}else setSource('new');}).catch(e=>active&&setError(e.message));
    const previous=document.activeElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.focus();return()=>{active=false;document.body.style.overflow=overflow;previous?.focus();};
  },[isOpen,initialBusinessId]);
  if(!isOpen)return null;
  const problems=[
    source==='existing'&&!business.id?'Select an existing business.':!business.name.trim()||!business.country.trim()||!business.timezone.trim()?'Enter business name, country and timezone.':Object.keys({phone:1,email:1,website:1,address:1}).some(k=>!business[k]?.trim()&&!unavailable[k])?'Complete contact details or select No information.':business.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(business.email)?'Enter a valid email address.':business.website&&!/^https?:\/\/.+/.test(business.website)?'Website must start with https:// or http://.':'',
    !noHours&&hours.some(h=>!h.closed&&(!h.open_time||!h.close_time||h.open_time>=h.close_time))?'Enter valid opening and closing times.':'',
    !noCatalogue&&(!services.length||services.some(s=>!s.service_name.trim()||s.price===''||Number(s.price)<0||Number(s.duration_minutes)<=0))?'Complete the catalogue or choose No catalogue available.':'',
    !agent.name.trim()||!agent.role.trim()||!agent.first_message.trim()?'Enter the agent name, role and greeting.':'',
    !voice||!model?'Select a voice profile and runtime model.':'',
    !accepted?'Confirm the conversation rules.':!features.length&&!noFeatures?'Select capabilities or choose No additional capabilities.':'',
  ];
  const go=target=>{if(target>step){const invalid=problems.slice(0,target).findIndex(Boolean);if(invalid>=0){setError(problems[invalid]);setStep(invalid);return;}}setError('');setStep(target);};
  const field=(label,key,optional=false)=><label className="form-group" key={key}><span className="form-label">{label}{!optional?' *':''}</span><input className="form-input" value={business[key]||''} disabled={unavailable[key]} onChange={e=>setBusiness({...business,[key]:e.target.value})}/>{optional&&<span className="optional-check"><input type="checkbox" aria-label={`No ${label.toLowerCase()} information available`} checked={!!unavailable[key]} onChange={e=>{setUnavailable({...unavailable,[key]:e.target.checked});if(e.target.checked)setBusiness({...business,[key]:''});}}/> No information available</span>}</label>;
  async function create(){const invalid=problems.findIndex(Boolean);if(invalid>=0){setStep(invalid);setError(problems[invalid]);return;}setBusy(true);setError('');try{const response=await apiFetch('/admin/onboarding/create-agent',{method:'POST',body:JSON.stringify({business_data:business,hours_data:noHours?[]:hours,services_data:noCatalogue?[]:services.map(s=>({...s,price:Number(s.price),duration_minutes:Number(s.duration_minutes)})),agent_data:agent,voice_data:voices.find(v=>v.voice_id===voice),llm_data:models.find(m=>m.model===model),features_data:noFeatures?[]:features,rules_data:{hours_unavailable:noHours,catalogue_unavailable:noCatalogue,unavailable_fields:Object.keys(unavailable).filter(k=>unavailable[k]),rules_accepted:accepted}})});setResult(response);onCreated?.(response);window.dispatchEvent(new Event('scadova:updated'));}catch(e){setError(e.message);}finally{setBusy(false);}}
  const keydown=e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const els=[...dialog.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')];const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
  return <div className="modal-overlay"><div ref={dialog} tabIndex={-1} onKeyDown={keydown} className="modal-content onboarding-dialog" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><header className="modal-header"><div><span className="eyebrow">WORKSPACE SETUP</span><h3 id="onboarding-title">{result?'Your agent is ready':'Set up your business & voice agent'}</h3><p className="card-subtitle">Complete each step. Missing optional details can be marked unavailable.</p></div><button className="modal-close-btn" aria-label="Close onboarding" onClick={onClose} disabled={busy}><X size={20}/></button></header>
  {!result&&<nav className="wizard-steps" aria-label="Setup progress">{steps.map((label,i)=><button key={label} disabled={i>step||busy} aria-current={step===i?'step':undefined} aria-label={label} className={i===step?'current':i<step?'done':''} onClick={()=>go(i)}><span>{i<step?<Check size={14}/>:i>step?<LockKeyhole size={13}/>:i+1}</span>{label}</button>)}</nav>}
  <div className="modal-body wizard-body">{error&&<p className="notice error" role="alert">{error}</p>}{result?<div className="setup-success"><Check size={40}/><h2>{result.agent?.name} created</h2><p>The business and agent configuration have been saved. Connect Fish Audio from Usage & Credits to sync provider sessions.</p><button className="btn btn-primary" onClick={onClose}>Done</button></div>:<>
  <div className="wizard-section-title"><span>STEP {step+1} OF {steps.length}</span><h2>{steps[step]}</h2></div>
  {step===0&&<><label className="form-group"><span className="form-label">Business source</span><select className="form-select" value={source} onChange={e=>{setSource(e.target.value);setBusiness({...blank});setUnavailable({});}}><option value="new">New business</option><option value="existing">Existing business</option></select></label>{source==='existing'&&<label className="form-group"><span className="form-label">Select a business</span><select className="form-select" value={business.id||''} onChange={e=>setBusiness({...blank,...existing.find(b=>String(b.id)===e.target.value)})}><option value="">Choose business</option>{existing.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}<div className="wizard-fields">{field('Business name','name')}<label className="form-group"><span className="form-label">Business type</span><select className="form-select" value={business.type} onChange={e=>setBusiness({...business,type:e.target.value})}>{['Service and Appointment Booking','Restaurant','Loan Agency','Custom'].map(t=><option key={t}>{t}</option>)}</select></label>{field('Country','country')}{field('Timezone (IANA)','timezone')}{field('Phone','phone',true)}{field('Email','email',true)}{field('Website','website',true)}{field('Address','address',true)}</div></>}
  {step===1&&<><label className="choice-row"><input type="checkbox" checked={noHours} onChange={e=>setNoHours(e.target.checked)}/> No operating hours available</label>{!noHours&&hours.map((h,i)=><div className="hours-row" key={h.day}><strong>{h.day}</strong><input aria-label={`${h.day} opening time`} type="time" className="form-input" disabled={h.closed} value={h.open_time} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,open_time:e.target.value}:x))}/><input aria-label={`${h.day} closing time`} type="time" className="form-input" disabled={h.closed} value={h.close_time} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,close_time:e.target.value}:x))}/><label><input type="checkbox" checked={h.closed} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,closed:e.target.checked}:x))}/> Closed</label></div>)}</>}
  {step===2&&<><label className="choice-row"><input type="checkbox" checked={noCatalogue} onChange={e=>setNoCatalogue(e.target.checked)}/> No catalogue available</label>{!noCatalogue&&<><p className="card-subtitle">Add services, menu items or products. Prices use your business currency.</p>{services.map((s,i)=><div className="catalogue-row" key={i}>{[['Name','service_name','text'],['Price','price','number'],['Duration (minutes)','duration_minutes','number']].map(([label,key,type])=><label className="form-group" key={key}><span className="form-label">{label}</span><input className="form-input" type={type} min={key==='duration_minutes'?1:0} step={key==='price'?'0.01':1} value={s[key]} onChange={e=>setServices(services.map((x,j)=>i===j?{...x,[key]:e.target.value}:x))}/></label>)}<button className="btn btn-secondary" aria-label={`Remove item ${i+1}`} onClick={()=>setServices(services.filter((_,j)=>i!==j))}><X size={15}/></button></div>)}<button className="btn btn-secondary" onClick={()=>setServices([...services,{service_name:'',price:'',duration_minutes:30}])}>Add item</button></>}</>}
  {step===3&&<div className="wizard-fields">{[['Agent name','name'],['Role','role'],['Opening greeting','first_message']].map(([label,key])=><label className="form-group" key={key}><span className="form-label">{label} *</span><input className="form-input" value={agent[key]} onChange={e=>setAgent({...agent,[key]:e.target.value})}/></label>)}<label className="form-group"><span className="form-label">Language</span><select className="form-select" value={agent.language} onChange={e=>setAgent({...agent,language:e.target.value})}><option value="en">English</option><option value="te">Telugu</option></select></label></div>}
  {step===4&&<div className="wizard-fields"><label className="form-group"><span className="form-label">Voice profile *</span><select className="form-select" value={voice} onChange={e=>setVoice(e.target.value)}><option value="">Select voice</option>{voices.map(v=><option key={v.voice_id} value={v.voice_id}>{v.voice_name}</option>)}</select></label><label className="form-group"><span className="form-label">Runtime model *</span><select className="form-select" value={model} onChange={e=>setModel(e.target.value)}><option value="">Select model</option>{models.map(m=><option key={m.model} value={m.model}>{m.name}</option>)}</select></label><p className="card-subtitle">These are local configuration profiles. Fish Audio linking is managed separately in Usage & Credits.</p></div>}
  {step===5&&<><label className="choice-row"><input type="checkbox" checked={noFeatures} onChange={e=>setNoFeatures(e.target.checked)}/> No additional capabilities</label>{!noFeatures&&['Business information','Pricing questions','Schedule appointment','Reschedule appointment','Cancel appointment','Customer verification'].map(f=><label className="choice-row" key={f}><input type="checkbox" checked={features.includes(f)} onChange={e=>setFeatures(e.target.checked?[...features,f]:features.filter(x=>x!==f))}/>{f}</label>)}<div className="notice">Ask one question at a time, verify customer details, quote only supplied prices, state the timezone, and confirm bookings before saving.</div><label className="choice-row"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> I reviewed and accept these conversation rules *</label></>}
  {step===6&&<div className="review-grid">{[['Business',business.name],['Type',business.type],['Timezone',business.timezone],['Agent',agent.name],['Hours',noHours?'Not available':'Configured'],['Catalogue',noCatalogue?'Not available':`${services.length} items`],['Voice',voices.find(v=>v.voice_id===voice)?.voice_name],['Model',model]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>}
  </>}</div>{!result&&<footer className="modal-footer"><button className="btn btn-secondary" disabled={step===0||busy} onClick={()=>go(step-1)}><ArrowLeft size={16}/>Back</button><span className="card-subtitle">{step+1} / {steps.length}</span>{step<6?<button className="btn btn-primary" onClick={()=>go(step+1)}>Continue<ArrowRight size={16}/></button>:<button className="btn btn-primary" disabled={busy} onClick={create}>{busy?'Savingâ€¦':'Create agent'}<Check size={16}/></button>}</footer>}</div></div>;
}
